name : Periodic

on : 
    schedule:
        -   cron: '20,25,30 10 * * *' 

jobs: 
    PingServer : 
        runs-on : ubuntu-latest
        steps: 
            -   name: ping-app-server
                uses: jtalk/url-health-check-action@v3
                with: 
                    url: https://fullstack-pokedex-adefuyeabayomi.onrender.com/pinggg/
                    max-attempts : 2
            -   name: notifySuccess
                if: success()
                uses: rjstone/discord-webhook-notify@v1
                with: 
                    severity: info
                    details: Ping Succeded. Server Address - https://fullstack-pokedex-adefuyeabayomi.onrender.com/ping/ 
                    webhookUrl :  ${{ secrets.DISCORD_WEBHOOK }}
            -   name: notifyFail
                if: failure()
                uses: rjstone/discord-webhook-notify@v1
                with: 
                    severity: warn
                    details: Ping Failed, Server offline. Server Address - https://fullstack-pokedex-adefuyeabayomi.onrender.com/ping/ 
                    webhookUrl :  ${{ secrets.DISCORD_WEBHOOK }}


